language: python

python:
  - "3.8"

install:
  - pip install -r flask/requirements.txt


jobs:
  include:
    - stage: pylint
      script:
        - pylint flask/app/
        - pylint flask/run.py
        - pylint flask/tests
    - stage: test
      script:
        - pytest
