version: "3.7"

services:

  flask:
    build: ./flask
    container_name: flask
    restart: always
    environment:
      - APP_NAME=PaymentApp
    expose:
      - 8080

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
  data:
    image: postgres:9.6
    volumes:
      - /var/lib/postgresql
    command: "true"
 
  postgres:
    restart: always
    build: ./postgresql
    volumes:
      - data
    ports:
      - "5432:5432"
